Create a reproduction showing the issue when using the debug package
```
⨯ ./app/next.svg
Error evaluating Node.js code
TypeError: 'process.env' only accepts a configurable, writable, and enumerable data descriptor
    [at Function.save (/private/tmp/reproduction-app/node_modules/debug/src/node.js:205:21)]
    [at Function.enable (/private/tmp/reproduction-app/node_modules/debug/src/common.js:163:15)]
    [at setup (/private/tmp/reproduction-app/node_modules/debug/src/common.js:287:14)]
    [at Object.<anonymous> (/private/tmp/reproduction-app/node_modules/debug/src/node.js:240:37)]
    [at Module._compile (node:internal/modules/cjs/loader:1562:14)]
    [at Object..js (node:internal/modules/cjs/loader:1699:10)]
    [at Module.load (node:internal/modules/cjs/loader:1313:32)]
    [at Function._load (node:internal/modules/cjs/loader:1123:12)]
    [at TracingChannel.traceSync (node:diagnostics_channel:322:14)]
    [at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)]

./app/page.tsx:1:1
Export default doesn't exist in target module
> 1 | import NextLogo from "./next.svg";
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 | export default function Home() {
  3 |   return (
  4 |     <div>

The export default was not found in module [project]/app/next.svg.js [app-rsc] (ecmascript).
The module has no exports at all.
All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.
```